# Iris FLowers Classification Project
## The attributes for this dataset
1. Sepal length in centimeters
2. Sepal width in centimeters
3. Petal length in centimeters
4. Petal width in centimeters
5. Class

## 1. Import Classes and Functions

In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

## 2. Initialize Random Number Generator

In [2]:
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

## 3. Load the Dataset

In [3]:
# load dataset
dataframe = pd.read_csv('iris.csv',header=None)
dataset = dataframe.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]

## 4. Encode the output variable
* The three class values **Iris-setosa,Iris-versicolor and Iris-virginica**.
* First encoding the strings consistently to integers using the scikit-learn class **LabelEncoder**.
* Then convert the vector of integers to a one hot encoding using the keras function **to_categorical()**.

In [4]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)

encoded_Y = encoder.transform(Y)
print(encoded_Y)

# convert integers to dummy variables (one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
print(dummy_y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

## 5. Define the Neural Netowork Model
* 4 inputs -> [4 hidden nodes] -> 3 outputs
* we use sigmoid activation function in the output layer,to ensure the output values are in the range of 0 and 1.
* we use logarithmic loss function,which is called *categorical_Crossentropy* in keras

In [5]:
# define the model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(4,input_dim=4,activation='relu'))
    model.add(Dense(3,activation='sigmoid'))
    
    # compile model
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    return model

In [6]:
estimator = KerasClassifier(build_fn=baseline_model,epochs=200,batch_size=5,verbose=0)

## 6. Evaluate the Model with k-fold Cross Validation

In [7]:
kfold = KFold(n_splits=10,shuffle=True,random_state=seed)

In [8]:
results = cross_val_score(estimator,X,dummy_y,cv=kfold)
print('Accuracy: %.2f%% (%.2f%%)' %(results.mean()*100,results.std()*100))

Accuracy: 94.00% (9.64%)


# Summary
* Discovered how to develop and evaluate a neural network using the keras library for deep learning